---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-stopwatch
  title: Demo Stopwatch
  description: A simple stopwatch demo application deployed via ArgoCD.
  annotations:
    argocd/app-selector: 'app=demo-stopwatch'
    backstage.io/source-location: url:https://github.com/Babas10/demo-stopwatch
spec:
  type: website
  lifecycle: experimental
  owner: user:default/admin
